import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    dir: 'ltr',
    // Nav
    home: 'Home', dashboard: 'Dashboard', market: 'Market', learn: 'Learn', profile: 'Profile',
    // Home hero
    tagline: '#1 Financial App for UAE Students',
    heroTitle1: 'Your personal',
    heroTitle2: 'money coach',
    heroTitle3: '',
    heroDesc: 'Get your Financial Health Score in 2 minutes. FINOVA AI analyzes your income, spending, and savings to give you a clear action plan — all in AED, built for UAE students and young professionals.',
    ctaPrimary: 'Check My Financial Score',
    ctaSecondary: 'Learn First',
    tryFree: 'Try Free',
    // Stats
    stat1Label: 'UAE Students', stat1Sub: 'Using FINOVA AI',
    stat2Label: 'Currency', stat2Sub: 'Fully localized',
    stat3Label: 'Analysis', stat3Sub: 'Get your score fast',
    stat4Label: 'Free', stat4Sub: 'No credit card',
    // Features
    feat1Title: 'Financial Score', feat1Desc: 'Your money health in one clear number — 0 to 100',
    feat2Title: 'AI Coach', feat2Desc: 'Personalized advice based on your real UAE spending patterns',
    feat3Title: 'Market Tracker', feat3Desc: 'Follow ADX & DFM stocks. Learn investing the smart way',
    feat4Title: 'Money Lessons', feat4Desc: 'Short, practical guides made for UAE students & young adults',
    feat5Title: 'Goal Tracker', feat5Desc: 'Set savings goals and track your progress every month',
    feat6Title: 'Emergency Fund', feat6Desc: 'Build a safety net — 3 months of expenses as a buffer',
    // How it works
    howItWorks: 'How FINOVA AI Works',
    step1Title: 'Enter Your Numbers', step1Desc: 'Income, rent, food, transport — takes 2 minutes',
    step2Title: 'AI Analyzes Your Data', step2Desc: 'Our engine scores your finances 0–100 using UAE benchmarks',
    step3Title: 'Get Your Action Plan', step3Desc: 'Personalized tips, predictions, and goals to improve your score',
    // UAE Banner
    uaeTitle: 'Built for the UAE',
    uaeDesc: 'AED currency · UAE university expenses · Metro & Salik transport · Etisalat/du mobile plans · ADX & DFM investing education · UAE banking guide',
    getMyScore: 'Get My Score',
    // Bottom CTA
    bottomCta: 'Try FINOVA AI — 100% Free',
    // InputForm
    enterData: 'Enter Your Financial Data',
    aiAnalysis: 'AI-Powered Financial Analysis',
    monthlyIncome: 'Monthly Income',
    incomeDesc: 'Salary, allowance, or any regular income',
    monthlyExpenses: 'Monthly Expenses',
    expensesDesc: 'Break down your spending by category',
    currentSavings: 'Current Savings',
    savingsDesc: 'Total savings or emergency fund balance',
    runAnalysis: 'Run AI Financial Analysis',
    analyzing: 'AI is analyzing your data...',
    dataPrivate: '🔒 Your data is processed locally and never shared',
    // Demo
    demoTitle: 'Get Your Financial Score — Free',
    demoSubtitle: 'No account needed. Takes 2 minutes.',
    // Learn page
    learnBadge: 'UAE Financial Literacy',
    learnModules: [
      'The 50/30/20 Rule',
      'Emergency Fund',
      'BNPL & Credit Cards',
      'UAE Student Benefits',
      'Earn Extra Income in UAE',
      'Rent & Accommodation',
      'Getting Around in UAE',
      'Mobile & Subscriptions',
    ],
    // Dashboard
    dash: {
      shareScore: 'Share Score',
      pdfReport: 'PDF Report',
      generatingPdf: 'Generating...',
      reanalyze: 'Re-analyze',
      healthScore: 'Financial Health Score',
      scoreCaption: 'Based on your UAE spending, savings rate & financial behavior',
      scoreBreakdownTitle: 'Score Breakdown',
      spendingBreakdownTitle: 'Spending Breakdown',
      ofIncome: (amt) => `% of AED ${amt} income`,
      statIncome: 'Monthly Income',
      statExpenses: 'Total Expenses',
      statSurplus: 'Monthly Surplus',
      statSavingsRate: 'Savings Rate',
      tabs: { overview: 'Overview', insights: 'AI Insights', plan: 'Action Plan', future: 'Future', scenarios: 'Scenarios', coach: 'AI Coach' },
      viewAllInsights: 'View All AI Insights',
      aiAnalysisTitle: 'AI Financial Analysis',
      aiAnalysisDesc: 'Personalized insights based on your UAE spending patterns and financial benchmarks.',
      actionPlanTitle: 'Your Personalized Action Plan',
      actionPlanDesc: 'AI-generated steps to improve your FINOVA score — specific to your situation.',
      scenarioTitle: 'What-If Scenario Simulator',
      scenarioDesc: 'See how targeted changes to your spending would affect your FINOVA score.',
      whatIf: (label) => `💡 What if you ${label}?`,
      before: 'BEFORE',
      after: 'AFTER',
      scoreDeltaLabel: (d) => `Score: ${d > 0 ? '+' : ''}${d} pts`,
      riskChangeLabel: (a, b) => `Risk: ${a} → ${b}`,
      coachTitle: 'FINOVA AI Coach',
      coachDesc: 'Your personal UAE financial coach. Ask me anything about your money, score, or how to improve.',
      suggestedQuestions: ['Explain my score', 'How can I save more?', 'Am I ready to invest?', 'What should I fix first?', 'Help me build an emergency fund'],
      chatPlaceholder: 'Ask your AI coach anything about your finances…',
      thinking: 'Thinking...',
      errorTitle: 'Something went wrong',
      dismiss: 'Dismiss',
      risk: { 'High Risk': 'High Risk', 'Medium Risk': 'Medium Risk', 'Low Risk': 'Low Risk' },
      trend: { Improving: 'Improving', Stable: 'Stable', Worsening: 'Worsening' },
      scoreBars: { savingsRate: 'Savings Rate', expenseRatio: 'Expense Ratio', spendingBehavior: 'Spending Behavior' },
      insightTypeLabels: { critical: 'Critical', warning: 'Warning', positive: 'Positive', neutral: 'Info' },
      priorityLabels: { urgent: 'Urgent', high: 'High Priority', medium: 'Recommended', low: 'Tip' },
      impactLabel: (v) => `Impact: ${v}`,
      riskTrendLabel: (label) => `Risk Trend: ${label}`,
      predictionSubtitle: 'Based on current savings rate and expense ratio',
      monthLabel: (n) => `Month ${n}`,
      nowLabel: 'Now',
      perMonthSuffix: '/mo',
      savingsTrajectory: 'Savings Trajectory',
      savingsGoalTitle: 'Savings Goal',
      savingsGoalDesc: 'Track progress toward your target',
      savingsGoalPlaceholder: 'e.g. 10000',
      setGoalBtn: 'Set Goal',
      currentSavingsLabel: 'Current Savings',
      goalLabel: 'Goal',
      goalReached: 'Goal reached! 🎉',
      percentComplete: (p) => `${p}% complete`,
      remainingSuffix: 'remaining',
      clearGoal: 'Clear goal',
      etaWarning: '⚠️ With your current surplus, reaching this goal requires reducing expenses first.',
      etaPrefix: '📅 At your current surplus of',
      etaMiddle: ", you'll reach your goal in approximately",
      monthsUnit: (n) => n === 1 ? '1 month' : `${n} months`,
      yearsUnit: (n) => `${n} years`,
      targetsTitle: 'Savings vs. Targets',
      benchmarkDesc: 'How you compare to recommended benchmarks',
      monthlySavingsLabel: 'Monthly Savings',
      yourSavingsLabel: 'Your Savings',
      recommendedLabel: 'Recommended (20%)',
      targetLabel: (amt) => `Target: AED ${amt}/mo`,
      gapLabel: (amt) => `Gap: AED ${amt}/mo`,
      surplusLabel: (amt) => `Surplus: +AED ${amt}/mo`,
      onTrack: 'On Track',
      behindTarget: 'Behind Target',
      offTrack: 'Off Track',
      fullyFunded: 'Fully Funded',
      minimumMet: 'Minimum Met',
      underfunded: 'Underfunded',
      emergencyFundLabel: 'Emergency Fund',
      monthsShort: (n, amt) => `${n} mo (AED ${amt})`,
      youHave: (amt) => `You have: AED ${amt}`,
      monthsOfRunway: (n) => `${n} months of runway`,
      summaryOnTrack: (rate) => `You're saving ${rate}% of your income — meeting the 20% benchmark. Keep this up to stay on track for your goals.`,
      summaryBehind: (rate, gap) => `You're saving ${rate}% vs the 20% target. Closing the gap of AED ${gap}/mo would put you on track.`,
      shareYourScore: 'Share Your Score',
      preparing: 'Preparing…',
      shareBadge: 'Share Badge',
      myScoreLabel: 'My Financial Health Score',
      tagline2: 'Track your money. Grow your future.',
      copied: 'Copied',
      copy: 'Copy',
      downloadBadge: 'Download Badge Image',
      shareDisclaimer: 'Your badge shows your score and risk level only — no income or spending details are shared.',
      shareText: (score, risk) => `My FINOVA Financial Health Score is ${score}/100 — ${risk}! 🎯 Find out yours at`,
    },
  },
  ar: {
    dir: 'rtl',
    // Nav
    home: 'الرئيسية', dashboard: 'لوحتي', market: 'السوق', learn: 'تعلم', profile: 'ملفي',
    // Home hero
    tagline: 'التطبيق المالي الأول لطلاب الإمارات',
    heroTitle1: 'مستشارك المالي',
    heroTitle2: 'الشخصي',
    heroTitle3: '',
    heroDesc: 'احصل على نقاط صحتك المالية في دقيقتين. فينوفا AI يحلل دخلك وإنفاقك ومدخراتك ليمنحك خطة عمل واضحة — بالدرهم الإماراتي، مصمم لطلاب وشباب الإمارات.',
    ctaPrimary: 'تحقق من نقاطي المالية',
    ctaSecondary: 'تعلم أولاً',
    tryFree: 'جرب مجاناً',
    // Stats
    stat1Label: 'طالب إماراتي', stat1Sub: 'يستخدمون فينوفا',
    stat2Label: 'العملة', stat2Sub: 'درهم إماراتي',
    stat3Label: 'التحليل', stat3Sub: 'احصل على نقاطك بسرعة',
    stat4Label: '100%', stat4Sub: 'مجاني تماماً',
    // Features
    feat1Title: 'النقاط المالية', feat1Desc: 'صحة أموالك في رقم واحد من 0 إلى 100',
    feat2Title: 'مستشار ذكي', feat2Desc: 'نصائح مخصصة بناءً على أنماط إنفاقك الفعلية في الإمارات',
    feat3Title: 'تتبع السوق', feat3Desc: 'تابع أسهم سوق أبوظبي ودبي. تعلم الاستثمار بذكاء',
    feat4Title: 'دروس مالية', feat4Desc: 'أدلة قصيرة وعملية مصممة لطلاب الإمارات والشباب',
    feat5Title: 'متابعة الأهداف', feat5Desc: 'حدد أهداف المدخرات وتابع تقدمك كل شهر',
    feat6Title: 'صندوق الطوارئ', feat6Desc: 'ابنِ شبكة أمان — 3 أشهر من النفقات كاحتياطي',
    // How it works
    howItWorks: 'كيف يعمل فينوفا AI',
    step1Title: 'أدخل أرقامك', step1Desc: 'الدخل، الإيجار، الطعام، المواصلات — يستغرق دقيقتين',
    step2Title: 'الذكاء الاصطناعي يحلل بياناتك', step2Desc: 'محركنا يقيّم أموالك من 0 إلى 100 باستخدام معايير الإمارات',
    step3Title: 'احصل على خطة عملك', step3Desc: 'نصائح مخصصة وتوقعات وأهداف لتحسين نقاطك',
    // UAE Banner
    uaeTitle: 'مصنوع للإمارات',
    uaeDesc: 'الدرهم الإماراتي · نفقات جامعات الإمارات · مترو وسالك · باقات اتصالات/دو · تعليم الاستثمار في سوق أبوظبي ودبي · دليل البنوك الإماراتية',
    getMyScore: 'احصل على نقاطي',
    // Bottom CTA
    bottomCta: 'جرب فينوفا AI — مجاناً 100%',
    // InputForm
    enterData: 'أدخل بياناتك المالية',
    aiAnalysis: 'تحليل مالي بالذكاء الاصطناعي',
    monthlyIncome: 'الدخل الشهري',
    incomeDesc: 'الراتب، بدل، أو أي دخل منتظم',
    monthlyExpenses: 'المصاريف الشهرية',
    expensesDesc: 'صنف إنفاقك حسب الفئة',
    currentSavings: 'المدخرات الحالية',
    savingsDesc: 'إجمالي المدخرات أو رصيد صندوق الطوارئ',
    runAnalysis: 'شغّل تحليل الذكاء الاصطناعي',
    analyzing: 'الذكاء الاصطناعي يحلل بياناتك...',
    dataPrivate: '🔒 بياناتك تُعالج محلياً ولا تُشارك أبداً',
    // Demo
    demoTitle: 'احصل على نقاطك المالية — مجاناً',
    demoSubtitle: 'لا حاجة لحساب. يستغرق دقيقتين.',
    // Learn page
    learnBadge: 'الثقافة المالية في الإمارات',
    learnModules: [
      'قاعدة 50/30/20',
      'صندوق الطوارئ',
      'الدفع الآجل وبطاقات الائتمان',
      'مزايا الطلاب في الإمارات',
      'كسب دخل إضافي في الإمارات',
      'الإيجار والسكن',
      'التنقل في الإمارات',
      'الهاتف والاشتراكات',
    ],
    // Dashboard
    dash: {
      shareScore: 'مشاركة النقاط',
      pdfReport: 'تقرير PDF',
      generatingPdf: 'جارٍ الإنشاء...',
      reanalyze: 'إعادة التحليل',
      healthScore: 'نقاط الصحة المالية',
      scoreCaption: 'بناءً على إنفاقك في الإمارات، معدل ادخارك، وسلوكك المالي',
      scoreBreakdownTitle: 'تفاصيل النقاط',
      spendingBreakdownTitle: 'تفصيل الإنفاق',
      ofIncome: (amt) => `% من دخل ${amt} درهم`,
      statIncome: 'الدخل الشهري',
      statExpenses: 'إجمالي المصاريف',
      statSurplus: 'الفائض الشهري',
      statSavingsRate: 'معدل الادخار',
      tabs: { overview: 'نظرة عامة', insights: 'رؤى الذكاء الاصطناعي', plan: 'خطة العمل', future: 'المستقبل', scenarios: 'سيناريوهات', coach: 'المستشار الذكي' },
      viewAllInsights: 'عرض كل الرؤى',
      aiAnalysisTitle: 'التحليل المالي بالذكاء الاصطناعي',
      aiAnalysisDesc: 'رؤى مخصصة بناءً على أنماط إنفاقك في الإمارات والمعايير المالية.',
      actionPlanTitle: 'خطة عملك الشخصية',
      actionPlanDesc: 'خطوات مولدة بالذكاء الاصطناعي لتحسين نقاط فينوفا الخاصة بك — مخصصة لحالتك.',
      scenarioTitle: 'محاكي السيناريوهات الافتراضية',
      scenarioDesc: 'شاهد كيف تؤثر تغييرات محددة في إنفاقك على نقاط فينوفا الخاصة بك.',
      whatIf: (label) => `💡 ماذا لو ${label}؟`,
      before: 'قبل',
      after: 'بعد',
      scoreDeltaLabel: (d) => `النقاط: ${d > 0 ? '+' : ''}${d}`,
      riskChangeLabel: (a, b) => `المخاطر: ${a} ← ${b}`,
      coachTitle: 'مستشار فينوفا الذكي',
      coachDesc: 'مستشارك المالي الشخصي في الإمارات. اسألني أي شيء عن أموالك أو نقاطك أو كيفية التحسين.',
      suggestedQuestions: ['اشرح نقاطي', 'كيف يمكنني ادخار المزيد؟', 'هل أنا جاهز للاستثمار؟', 'ما الذي يجب إصلاحه أولاً؟', 'ساعدني في بناء صندوق طوارئ'],
      chatPlaceholder: 'اسأل مستشارك الذكي أي شيء عن أموالك…',
      thinking: 'جارٍ التفكير...',
      errorTitle: 'حدث خطأ ما',
      dismiss: 'إغلاق',
      risk: { 'High Risk': 'مخاطر عالية', 'Medium Risk': 'مخاطر متوسطة', 'Low Risk': 'مخاطر منخفضة' },
      trend: { Improving: 'في تحسن', Stable: 'مستقر', Worsening: 'في تراجع' },
      scoreBars: { savingsRate: 'معدل الادخار', expenseRatio: 'نسبة المصاريف', spendingBehavior: 'سلوك الإنفاق' },
      insightTypeLabels: { critical: 'حرج', warning: 'تحذير', positive: 'إيجابي', neutral: 'معلومة' },
      priorityLabels: { urgent: 'عاجل', high: 'أولوية عالية', medium: 'موصى به', low: 'نصيحة' },
      impactLabel: (v) => `التأثير: ${v}`,
      riskTrendLabel: (label) => `اتجاه المخاطر: ${label}`,
      predictionSubtitle: 'بناءً على معدل الادخار الحالي ونسبة المصاريف',
      monthLabel: (n) => `الشهر ${n}`,
      nowLabel: 'الآن',
      perMonthSuffix: '/شهرياً',
      savingsTrajectory: 'مسار الادخار',
      savingsGoalTitle: 'هدف الادخار',
      savingsGoalDesc: 'تتبع تقدمك نحو هدفك',
      savingsGoalPlaceholder: 'مثال: 10000',
      setGoalBtn: 'حدّد الهدف',
      currentSavingsLabel: 'المدخرات الحالية',
      goalLabel: 'الهدف',
      goalReached: 'تم تحقيق الهدف! 🎉',
      percentComplete: (p) => `${p}% مكتمل`,
      remainingSuffix: 'متبقي',
      clearGoal: 'مسح الهدف',
      etaWarning: '⚠️ بفائضك الحالي، يتطلب تحقيق هذا الهدف تقليل المصاريف أولاً.',
      etaPrefix: '📅 بمعدل فائضك الحالي البالغ',
      etaMiddle: '، ستصل إلى هدفك خلال تقريباً',
      monthsUnit: (n) => n === 1 ? 'شهر واحد' : `${n} أشهر`,
      yearsUnit: (n) => `${n} سنوات`,
      targetsTitle: 'الادخار مقابل الأهداف',
      benchmarkDesc: 'كيف تقارن بالمعايير الموصى بها',
      monthlySavingsLabel: 'الادخار الشهري',
      yourSavingsLabel: 'ادخارك',
      recommendedLabel: 'الموصى به (20%)',
      targetLabel: (amt) => `الهدف: ${amt} درهم/شهرياً`,
      gapLabel: (amt) => `الفجوة: ${amt} درهم/شهرياً`,
      surplusLabel: (amt) => `الفائض: +${amt} درهم/شهرياً`,
      onTrack: 'على المسار الصحيح',
      behindTarget: 'متأخر عن الهدف',
      offTrack: 'خارج المسار',
      fullyFunded: 'ممول بالكامل',
      minimumMet: 'الحد الأدنى محقق',
      underfunded: 'غير كافٍ',
      emergencyFundLabel: 'صندوق الطوارئ',
      monthsShort: (n, amt) => `${n} أشهر (${amt} درهم)`,
      youHave: (amt) => `لديك: ${amt} درهم`,
      monthsOfRunway: (n) => `${n} أشهر من التغطية`,
      summaryOnTrack: (rate) => `أنت تدخر ${rate}% من دخلك — محققاً معيار 20%. استمر على هذا النهج للبقاء على المسار الصحيح نحو أهدافك.`,
      summaryBehind: (rate, gap) => `أنت تدخر ${rate}% مقابل هدف 20%. سد الفجوة البالغة ${gap} درهم/شهرياً سيضعك على المسار الصحيح.`,
      shareYourScore: 'شارك نقاطك',
      preparing: 'جارٍ التحضير…',
      shareBadge: 'شارك الشارة',
      myScoreLabel: 'نقاط صحتي المالية',
      tagline2: 'تتبع أموالك. نمِّ مستقبلك.',
      copied: 'تم النسخ',
      copy: 'نسخ',
      downloadBadge: 'تحميل صورة الشارة',
      shareDisclaimer: 'تعرض شارتك نقاطك ومستوى المخاطر فقط — لا تتم مشاركة أي تفاصيل عن الدخل أو الإنفاق.',
      shareText: (score, risk) => `نقاط صحتي المالية في فينوفا هي ${score}/100 — ${risk}! 🎯 اكتشف نقاطك في`,
    },
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('finova_lang') || 'en');

  useEffect(() => {
    localStorage.setItem('finova_lang', lang);
    document.documentElement.dir = translations[lang].dir;
    document.documentElement.lang = lang;
  }, [lang]);

  const toggle = () => setLang(l => l === 'en' ? 'ar' : 'en');
  const t = translations[lang];

  return (
    <LanguageContext.Provider value={{ lang, toggle, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}